# Generated by Django 2.2.4 on 2020-06-24 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='creator',
            new_name='createdBy',
        ),
        migrations.AddField(
            model_name='trip',
            name='trips',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='Main.User'),
        ),
    ]
